import{mkdirSync}from"node:fs";import{dirname,join}from"node:path";import{DatabaseSync}from"node:sqlite";
export const SCHEMA_VERSION=2,DEFAULT_COLORS={low:"#66d9a5",medium:"#62a8ff",high:"#f6ad55",urgent:"#ff6b7a"};
export const databasePath=p=>join(p,"data","todoapp.sqlite3");
const schema=()=>`CREATE TABLE tasks(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',starts_at TEXT,ends_at TEXT,backlog_order INTEGER,status TEXT NOT NULL CHECK(status IN('not_started','started','paused','blocked','completed')),criticality TEXT NOT NULL CHECK(criticality IN('low','medium','high','urgent')),recurrence TEXT NOT NULL DEFAULT 'none' CHECK(recurrence IN('none','daily','weekly','monthly')),recurrence_end TEXT,completed_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,CHECK((starts_at IS NULL AND ends_at IS NULL)OR(starts_at IS NOT NULL AND ends_at IS NOT NULL)),CHECK(starts_at IS NOT NULL OR recurrence='none'));CREATE INDEX idx_tasks_starts_at ON tasks(starts_at);CREATE INDEX idx_tasks_status ON tasks(status);CREATE INDEX idx_tasks_criticality ON tasks(criticality);CREATE INDEX idx_tasks_backlog_order ON tasks(backlog_order);`;
const row=r=>({id:Number(r.id),title:r.title,description:r.description,startsAt:r.starts_at,endsAt:r.ends_at,backlogOrder:r.backlog_order==null?null:Number(r.backlog_order),status:r.status,criticality:r.criticality,recurrence:r.recurrence,recurrenceEnd:r.recurrence_end,completedAt:r.completed_at,createdAt:r.created_at,updatedAt:r.updated_at});
const norm=t=>{for(const k of["title","status","criticality","createdAt","updatedAt"])if(t[k]==null||t[k]==="")throw Error(`Missing task field: ${k}`);const a=t.startsAt!=null&&t.startsAt!=="",b=t.endsAt!=null&&t.endsAt!=="";if(a!==b)throw Error("startsAt and endsAt must both be set or both be null");const rec=String(t.recurrence||"none");if(!a&&rec!=="none")throw Error("Backlog tasks cannot be recurrent until scheduled");return{title:String(t.title),description:String(t.description||""),startsAt:a?String(t.startsAt):null,endsAt:b?String(t.endsAt):null,backlogOrder:t.backlogOrder==null?null:Number(t.backlogOrder),status:String(t.status),criticality:String(t.criticality),recurrence:rec,recurrenceEnd:a?(t.recurrenceEnd||null):null,completedAt:t.completedAt||null,createdAt:String(t.createdAt),updatedAt:String(t.updatedAt)}};
export class TodoStore{constructor(filePath){this.filePath=filePath;mkdirSync(dirname(filePath),{recursive:true});this.db=new DatabaseSync(filePath);this.db.exec("PRAGMA journal_mode=WAL;PRAGMA foreign_keys=ON;");this.migrate()}
migrate(){const v=Number(this.db.prepare("PRAGMA user_version").get().user_version||0);if(v>2)throw Error(`Database schema ${v} is newer than supported 2`);if(v<1){this.db.exec(`BEGIN;${schema()}CREATE TABLE settings(key TEXT PRIMARY KEY,value_json TEXT NOT NULL,updated_at TEXT NOT NULL);PRAGMA user_version=2;COMMIT;`);this.setSetting("criticalityColors",DEFAULT_COLORS);return}if(v<2)this.db.exec(`BEGIN;ALTER TABLE tasks RENAME TO tasks_v1;${schema()}INSERT INTO tasks(id,title,description,starts_at,ends_at,backlog_order,status,criticality,recurrence,recurrence_end,completed_at,created_at,updated_at)SELECT id,title,description,starts_at,ends_at,NULL,status,criticality,recurrence,recurrence_end,completed_at,created_at,updated_at FROM tasks_v1;DROP TABLE tasks_v1;PRAGMA user_version=2;COMMIT;`)}
allTasks(){return this.db.prepare("SELECT * FROM tasks ORDER BY CASE WHEN starts_at IS NULL THEN 1 ELSE 0 END,starts_at,backlog_order,id").all().map(row)}
getTask(id){const r=this.db.prepare("SELECT * FROM tasks WHERE id=?").get(Number(id));return r?row(r):null}
saveTask(t){const d=norm(t),a=[d.title,d.description,d.startsAt,d.endsAt,d.backlogOrder,d.status,d.criticality,d.recurrence,d.recurrenceEnd,d.completedAt,d.createdAt,d.updatedAt];if(t.id){const x=this.db.prepare("UPDATE tasks SET title=?,description=?,starts_at=?,ends_at=?,backlog_order=?,status=?,criticality=?,recurrence=?,recurrence_end=?,completed_at=?,created_at=?,updated_at=? WHERE id=?").run(...a,Number(t.id));if(!x.changes)throw Error(`Task ${t.id} does not exist`);return Number(t.id)}return Number(this.db.prepare("INSERT INTO tasks(title,description,starts_at,ends_at,backlog_order,status,criticality,recurrence,recurrence_end,completed_at,created_at,updated_at)VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").run(...a).lastInsertRowid)}
deleteTask(id){return Number(this.db.prepare("DELETE FROM tasks WHERE id=?").run(Number(id)).changes)}
getSetting(k,f=null){const r=this.db.prepare("SELECT value_json FROM settings WHERE key=?").get(k);return r?JSON.parse(r.value_json):f}
setSetting(k,v){this.db.prepare("INSERT INTO settings(key,value_json,updated_at)VALUES(?,?,?) ON CONFLICT(key)DO UPDATE SET value_json=excluded.value_json,updated_at=excluded.updated_at").run(k,JSON.stringify(v),new Date().toISOString());return v}
info(){return{filePath:this.filePath,schemaVersion:2}}close(){this.db.close()}}
