if(!document.querySelector('link[data-backlog-css]')){const l=document.createElement("link");l.rel="stylesheet";l.href="./src/backlog.css";l.dataset.backlogCss="";document.head.append(l)}
if(!document.querySelector('style[data-backlog-form-style]')){const s=document.createElement("style");s.dataset.backlogFormStyle="";s.textContent=`.backlog-group-form{display:grid;gap:8px;margin:10px 0 2px;padding:10px;border:1px solid var(--border);border-radius:12px;background:var(--surface2)}.backlog-group-form.hidden{display:none}.backlog-group-form input{width:100%;height:34px;border:1px solid var(--border);border-radius:9px;background:#0e1217;color:#eef3f8;padding:0 10px}.backlog-group-form>div{display:flex;gap:7px;justify-content:flex-end}.backlog-group-form button{height:30px;border:1px solid var(--border);border-radius:8px;background:var(--surface);color:#d9e2ec;padding:0 10px}.backlog-group-form [data-group-submit]{background:var(--accent);color:#10131a;border:0;font-weight:700}`;document.head.append(s)}
import{saveTask,allBacklogGroups,saveBacklogGroup,deleteBackogGroup}from"./db.js";
import{backlogTasks,tasksInGroup,reorderBacklog}from"./backlog-model.js";
const e=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const eye=`<svg viewBox="0 0 24 24"><path d="M.4 12s3.5-6 9.6-6 9.6 6 9.6 6-3.5 6-9.6 6-9.6-6-9.6-6Z"/><circle cx="12" cy="12" r="2.7"/></svg>`;
let colors={};const open=new Set;
const card=t=>`<article class="backlog-card" draggable="true" data-backlog-task="${t.id}" data-group="${t.backlogGroupId??""}" style="--task-color:${colors[t.criticality]}"><span class="backlog-grip">⠿</span><div class="backlog-copy"><b>${e(t.title)}</b><small>${e(t.description||"Sin descripción")}</small></div><button class="backlog-eye" data-backlog-open="${t.id}">${eye}</button></article>`;
const tree=(gs,ts,p=null,d=0)=>gs.filter(g=>(g.parentId??null)===p).sort((a,b)=>a.groupOrder-b.groupOrder||a.id-b.id).map(g=>{const items=tasksInGroup(ts,g.id),o=open.has(g.id);return`<section class="backlog-group" style="--depth:${d}" data-backlog-group="${g.id}"><div class="backlog-group-head" data-group-target="${g.id}"><button class="backlog-collapse" data-group-toggle="${g.id}" aria-expanded="${o}">${o?"▾":"▸"}</button><span>📁</span><b>${e(g.name)}</b><em>${items.length}</em><button data-group-add="${g.id}">＋</button><button data-group-rename="${g.id}">✎</button><button data-group-delete="${g.id}">×</button></div><div class="backlog-group-body${o?"":" hidden"}" data-group-body="${g.id}"><div class="backlog-group-drop" data-group-drop="${g.id}">${items.map(card).join("")||'<div class="backlog-folder-empty">Soltá tareas aquí</div>'}</div>${tree(gs,ts,g.id,d+1)}</div></section>`}).join("");
export function backlogHTML(tasks,c){colors=c;return`<aside class="backlog-panel" data-backlog><header><div><p>BACKLOG</p><h2>Sin fecha</h2></div><div class="backlog-header-actions"><button class="backlog-folder-add" data-root-group-add>📁＋</button><button class="backlog-add" data-backlog-add>+</button></div></header><form class="backlog-group-form hidden" data-group-form><input data-group-name maxlength="80" autocomplete="off" placeholder="Nombre de la carpeta"><div><button type="submit" data-group-submit>Crear</button><button type="button" data-group-cancel>Cancelar</button></div></form><p class="backlog-help">Arrastrá tareas libremente entre carpetas o al calendario.</p><div class="backlog-tree" data-backlog-tree></div></aside>`}
async function persist(xs){const now=new Date().toISOString();for(const x of xs)await saveTask({...x,updatedAt:now})}
async function move(ts,id,target,before=null){const t=backlogTasks(ts).find(x=>x.id===+id);if(!t)return;const src=t.backlogGroupId??null;await persist(reorderBackog(ts,id,before,target));if(src!==target)await persist(tasksInGroup(ts,src).filter(x=>x.id!==+id).map((x,i)=>({...x,backlogOrder:i})))}
function drop(zone,ts,changed,target){zone.ondragover=x=>{x.preventDefault();x.stopPropagation();zone.classList.add("drag-over")};zone.ondragleave=()=>zone.classList.remove("drag-over");zone.ondrop=async x=>{if(x.target.closest("[data-backlog-task]"))return;x.preventDefault();x.stopPropagation();zone.classList.remove("drag-over");const id=+x.dataTransfer.getData("text/task-id");if(id){await move(ts,id,target);await changed()}}}
function bindCards(root,ts,edit,changed){root.querySelectorAll("[data-backlog-open]").forEach(b=>b.onclick=x=>{x.stopPropagation();edit(+b.dataset.backlogOpen)});root.querySelectorAll("[data-backlog-task]").forEach(c=>{c.ondragstart=x=>{x.dataTransfer.setData("text/task-id",c.dataset.backlogTask);x.dataTransfer.setData("text/task-source","backlog");c.classList.add("dragging")};c.ondragend=()=>c.classList.remove("dragging");c.ondragover=x=>{x.preventDefault();x.stopPropagation()};c.ondrop=async x=>{x.preventDefault();x.stopPropagation();const id=+x.dataTransfer.getData("text/task-id");if(id&&id!==+c.dataset.backlogTask){await move(ts,id,c.dataset.group===""?null:+c.dataset.group,+c.dataset.backlogTask);await changed()}}})}
function formOpen(root,parentId=null,g=null){const f=root.querySelector("[data-group-form]"),i=f?.querySelector("[data-group-name]"),s=f?.querySelector("[data-group-submit]");if(!f||!i)return;f.dataset.mode=g?"rename":"create";f.dataset.parentId=parentId==null?"":parentId;f.dataset.groupId=g?.id||"";i.value=g?.name||"";s.textContent=g?"Guardar":"Crear";f.classList.remove("hidden");requestAnimationFrame(()=>i.focus())}
function formClose(root){const f=root.querySelector("[data-group-form]");f?.classList.add("hidden");f?.reset()}
function bindForm(root,gs,changed){const f=root.querySelector("[data-group-form]"),i=f?.querySelector("[data-group-name]");if(!f||!i)return;root.querySelector("[data-group-cancel]")?.addEventListener("click",()=>formClose(root));f.addEventListener("submit",async x=>{x.preventDefault();const name=i.value.trim();if(!name)return i.focus();const gid=+f.dataset.groupId||null,pid=f.dataset.parentId===""?null:+f.dataset.parentId;if(f.dataset.mode==="rename"&&gid){const g=gs.find(x=>x.id===gid);if(g&&g.name!==name)await saveBacklogGroup({...g,name,updatedAt:new Date().toISOString()})}else{const sib=gs.filter(x=>(x.parentId??null)===(pid??null)),order=sib.length?Math.max(...sib.map(x=>x.groupOrder??0))+1:0,id=await saveBacklogGroup({name,parentId:pid,groupOrder:order});open.clear();open.add(+id);let a=pid;while(a!=null){open.add(+a);a=gs.find(x=>x.id===+a)?.parentId??null}}formClose(root);await changed()})}
export async function bindBacklog({root,tasks,openTask,onChanged}){root.querySelector("[data-backlog-add]")?.addEventListener("click",()=>openTask(null,null,{backlog:true}));const gs=await allBacklogGroups(),rt=tasksInGroup(tasks,null),host=root.querySelector("[data-backlog-tree]");host.innerHTML=`<section class="backlog-root"><div class="backlog-group-head root-head"><b>Sin categoría</b><em>${rt.length}</em></div><div class="backlog-group-drop" data-root-drop>${rt.map(card).join("")||'<div class="backlog-folder-empty">Soltá tareas aquí</div>'}</div></section>${tree(gs,tasks)}`;bindForm(root,gs,onChanged);root.querySelector("[data-root-group-add]")?.addEventListener("click",()=>formOpen(root));root.querySelectorAll("[data-group-toggle]").forEach(b=>b.onclick=x=>{x.stopPropagation();const id=+b.dataset.groupToggle;open.has(id)?open.delete(id):open.add(id);const body=root.querySelector(`[data-group-body="${id}"]`),o=open.has(id);body?.classList.toggle("hidden",!o);b.textContent=o?"▾":"▸";b.setAttribute("aria-expanded",o)});root.querySelectorAll("[data-group-add]").forEach(b=>b.onclick=()=>formOpen(root,+b.dataset.groupAdd));root.querySelectorAll("[data-group-rename]").forEach(b=>b.onclick=()=>{const g=gs.find(x=>x.id===+b.dataset.groupRename);if(g)formOpen(root,g.parentId??null,g)});root.querySelectorAll("[data-group-delete]").forEach(b=>b.onclick=async()=>{const g=gs.find(x=>x.id===+b.dataset.groupDelete);if(g&&confirm(`·Eliminar la carpeta vacía "${g.name}"?`)){try{open.delete(g.id);await deleteBacklogGroup(g.id);await onChanged()}catch(err){alert(err?.message||"La carpeta debe estar vacía.")}}});bindCards(root,tasks,openTask,onChanged);root.querySelectorAll("[data-group-drop]").forEach(z=>drop(z,tasks,onChanged,+z.dataset.groupDrop));const ry=root.querySelector("[data-root-drop]");if(ry)drop(ry,tasks,onChanged,null);root.querySelectorAll("[data-group-target]").forEach(h=>drop(h,tasks,onChanged,+h.dataset.groupTarget))}
